image: maven:3.3.9-jdk-8

variables:
  IP_DATABASE: "192.154.88.161"
  IP_REST: "192.154.88.162"
  IP_WEBAPP: "192.154.88.163"
  IP_NOTIFICATION: "192.154.88.164"
  IP_PUSH: "192.154.88.165"
  IP_SIEXT: "192.154.88.151"

stages:
  - compile
  - test
  - build
  - deploy

before_script:
  - mkdir ~/.ssh
  - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
  - chmod 700 ~/.ssh/id_rsa
  - ssh-keygen -f ~/.ssh/id_rsa -y > ~/.ssh/id_rsa.pub
  - echo "$SSH_HOST_KEYS" > ~/.ssh/known_hosts

maven_compile:
  stage: compile
  script:
    - mvn compile

maven_test:
  stage: test
  script:
    - mvn test
  when: on_success

maven_install_notmaster:
  stage: build
  script:
    - mvn install -DskipTests
  when: on_success
  except:
    - master

maven_install:
  stage: build
  script:
    - mvn install -DskipTests
  when: on_success
  artifacts:
      expire_in: 6 hrs
      paths:
      - data-access-server/target/dataaccess.war
      - rest-server/target/serverrest.war
      - web-app-server/target/serverweb.war
      - notification-server/target/notificationserver.jar
      - notification-push-server/target/notificationpushserver-jar-with-dependencies.jar
      - shares-price-history/target/shares-price-history-1.0-SNAPSHOT.jar
      - bank-transfer/target/bank-transfer-1.0-SNAPSHOT.jar
      - si-externe/target/si-externe.war
  only:
    refs:
      - master

deploy_database:
  stage: deploy
  dependencies:
    - maven_install
  script:
    - scp -v data-access-server/target/dataaccess.war esibank@$IP_DATABASE:/var/lib/tomcat8/webapps/dataaccess.war
  when: on_success
  only:
    refs:
      - master

deploy_rest:
  stage: deploy
  dependencies:
    - maven_install
  script:
    - scp rest-server/target/serverrest.war esibank@$IP_REST:/var/lib/tomcat8/webapps/serverrest.war
  when: on_success
  only:
    refs:
      - master

deploy_webapp:
  stage: deploy
  dependencies:
    - maven_install
  script:
    - scp -v web-app-server/target/serverweb.war esibank@$IP_WEBAPP:/var/lib/tomcat8/webapps/serverweb.war
    - scp bank-transfer/target/bank-transfer-1.0-SNAPSHOT.jar esibank@$IP_WEBAPP:/home/esibank/transactionesibank/bank-transfer.jar
    - scp shares-price-history/target/shares-price-history-1.0-SNAPSHOT.jar esibank@$IP_WEBAPP:/home/esibank/transactionesibank/shares-price-history.jar

  when: on_success
  only:
    refs:
      - master

deploy_notification:
  stage: deploy
  dependencies:
    - maven_install
  script:
    - scp notification-server/target/notificationserver.jar esibank@$IP_NOTIFICATION:/home/esibank/notificationserver.jar
    - ssh esibank@$IP_NOTIFICATION "sudo service notifserver restart"
  when: on_success
  only:
    refs:
      - master

deploy_push:
  stage: deploy
  dependencies:
    - maven_install
  script:
    - scp notification-push-server/target/notificationpushserver-jar-with-dependencies.jar esibank@$IP_PUSH:/home/esibank/notificationpushserver.jar
    - ssh esibank@$IP_PUSH "sudo service pushserver restart"
  when: on_success
  only:
    refs:
      - master

deploy_siext:
  stage: deploy
  dependencies:
    - maven_install
  script:
    - scp si-externe/target/si-externe.war esibank@$IP_SIEXT:/var/lib/tomcat8/webapps/si-externe.war
  when: on_success
  only:
    refs:
      - master