image: maven:3.3.9-jdk-8

variables:
  IP_DOCKER: "192.154.88.167"
  IP_NOTIF: "192.154.88.168"
stages:
  - compile
  - test
  - build
  - deploy
  - final

CompileAll:
  stage: compile
  script:
    - mvn compile
TestAll:
  stage: test
  script:
    - echo "SKIP"
    #- mvn test
  when: on_success
PackageAll:
  stage: build
  script:
    - echo "SKIP"
    #- mvn package -DskipTests
  when: on_success
  artifacts:
      expire_in: 2 hrs
      paths:
      - si-externe/target/si-externe.war
      - shares-price-historisation/target/shares-price-historisation.war
      - bank-transfer/target/bank-transfer-1.0-SNAPSHOT.jar
      - predict-InvestCustomer/target/predict-InvestCustomer-1.0-SNAPSHOT.jar
  only:
    refs:
      - master

#################################
##  NE PAS TOUCHER (THIBAULT)  ##
#################################
esibank_lab:
  stage: deploy
  script:
    - mvn install -DskipTests -pl data-access-server,rest-server,web-app-server -am
  only:
    refs:
      - master
notif_lab:
  stage: deploy
  script:
    - mvn install -DskipTests -pl notification-server,notification-push-server -am
  only:
    refs:
      - master
Exec_script:
  stage: final
  script:
    - mkdir ~/.ssh
    - echo "$TIBO_SSH_PRIVATE" > ~/.ssh/id_rsa
    - chmod 700 ~/.ssh/id_rsa
    - ssh-keygen -f ~/.ssh/id_rsa -y > ~/.ssh/id_rsa.pub
    - echo "$TIBO_SSH_HOST" > ~/.ssh/known_hosts
    - ssh esibank@$IP_DOCKER "sudo ./scriptDeployEsibank.sh"
    - ssh esibank@$IP_NOTIF "sudo ./scriptDeployNotifPush.sh"
  only:
    refs:
      - master
