image: maven:3.3.9-jdk-8

variables:
  IP_NOTIFICATION: "192.154.88.164"
  HOST_KEY_NOTIFICATION: "192.154.88.164 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBBebAl7r/s0cIpyttduO0qcPg2X/+4PXsNxwLpA3SxQzSYoa7bZHTTFEupwgVS+68cz1aISfMr8PDCQPrCYbMUs="

stages:
  - build
  - deploy

maven_install:
  stage: build
  environment: staging
  script:
    - mvn install

deploy_notification:
  stage: deploy
  environment: staging
  dependencies:
    - maven_install
  script:
    - mkdir ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 700 ~/.ssh/id_rsa
    - ssh-keygen -f ~/.ssh/id_rsa -y > ~/.ssh/id_rsa.pub
    - echo "$HOST_KEY_NOTIFICATION" > ~/.ssh/known_hosts
    - echo "test" > toto
    - scp notification-server/target/notificationserver.war esibank@$IP_NOTIFICATION:/home/esibank/notif.war
  only: master
