image: maven:3.3.9-jdk-8

variables:
  IP_NOTIFICATION: "192.154.88.164"
  IP_PUSH: "192.154.88.165"

stages:
  - build
  - deploy

deploy_notification:
  stage: deploy
  script:
    - mkdir ~/.ssh
    - echo "$TIBO_SSH_PRIVATE" > ~/.ssh/id_rsa
    - chmod 700 ~/.ssh/id_rsa
    - ssh-keygen -f ~/.ssh/id_rsa -y > ~/.ssh/id_rsa.pub
    - echo "$TIBO_SSH_HOST" > ~/.ssh/known_hosts
    - touch mytest
    - scp mytest $IP_NOTIFICATION:mytest.jar

deploy_push:
  stage: deploy
  script:
    - mkdir ~/.ssh
    - echo "TIBO_SSH_PRIVATE" > ~/.ssh/id_rsa
    - chmod 700 ~/.ssh/id_rsa
    - ssh-keygen -f ~/.ssh/id_rsa -y > ~/.ssh/id_rsa.pub
    - echo "TIBO_SSH_HOST" > ~/.ssh/known_hosts
    - touch mytest
    - scp mytest $IP_PUSH:mytest