image: maven:3.3.9-jdk-8

deploy_development:
    script:
    - mvn install
    - echo "$SSH_PRIVATE_KEY" > id_rsa
    - chmod 700 id_rsa
    - mkdir ~/.ssh
    - echo "$SSH_HOST_KEY" > ~/.ssh/known_hosts
    - scp -i id_rsa rest-server/target/serverrest.war 192.154.88.151:/home/esibank/app.war
