image: maven:3.3.9-jdk-8
cache:
  paths:
    - /root/.m2/repository/
before_script:
  - apt-get update -y && apt-get upgrade -y
    
NMQC-build:
  script:
    - mvn clean install
  artifacts:
    paths:
      - ./target/*.jar