image: maven:3.3.9-jdk-8

variables:
  IP_DOCKER: "192.154.88.167"
  IP_NOTIF: "192.154.88.168"
stages:
  - compile
  - test
  - build
  - deploy
  - final

CompileAll:
  stage: compile
  script:
    - mvn compile
TestAll:
  stage: test
  script:
    - echo "SKIP"
    #- mvn test
  when: on_success
PackageAll:
  stage: build
  script:
    - echo "SKIP"
    #- mvn package -DskipTests
  when: on_success
  artifacts:
      expire_in: 2 hrs
      paths:
      - si-externe/target/si-externe.war
      - shares-price-historisation/target/shares-price-historisation.war
      - bank-transfer/target/bank-transfer-1.0-SNAPSHOT.jar
      - predict-InvestCustomer/target/predict-InvestCustomer-1.0-SNAPSHOT.jar
  only:
    refs:
      - master

#################################
##  NE PAS TOUCHER (USMAN)  ##
#################################
dab_app:
  stage: deploy
  script:
    - mkdir dab-app-tgz-repo/
    - tar -zcvf dab-app-tgz-repo/dab-appdab-app.tgz dab-app/
  artifacts:
      expire_in: 1 hrs
      paths:
      - dab-app-tgz-repo/dab-appdab-app.tgz
  only:
    refs:
      - master

nfc_lib_c:
  stage: deploy
  script:
    - mkdir nfc-reader-lib-repo/
    - cd nfc-reader-lib/build
    - cmake ../source
    - make
    - cd ../../
    - tar -zcvf nfc-reader-lib-repo/nfc-reader-lib.tgz nfc-reader-lib/
  artifacts:
      expire_in: 1 hrs
      paths:
      - nfc-reader-lib-repo/nfc-reader-lib.tgz
  only:
    refs:
      - master

#################################
##  NE PAS TOUCHER (THIBAULT)  ##
#################################
esibank_lab:
  stage: deploy
  script:
    - mvn install -DskipTests -pl data-access-server,rest-server,web-app-server,rest-secure -am
  only:
    refs:
      - master
notif_lab:
  stage: deploy
  script:
    - mvn install -DskipTests -pl notification-server,notification-push-server -am
  only:
    refs:
      - master
payfree_clt:
  stage: deploy
  script:
    - mvn package -DskipTests -pl payfree-client -am
  artifacts:
      expire_in: 1 hrs
      paths:
      - payfree-client/target/payfreeclt.jar
  only:
    refs:
      - master
Exec_script:
  stage: final
  dependencies:
    - payfree_clt
    - dab_app
  script:
    - mkdir ~/.ssh
    - echo "$TIBO_SSH_PRIVATE" > ~/.ssh/id_rsa
    - chmod 700 ~/.ssh/id_rsa
    - ssh-keygen -f ~/.ssh/id_rsa -y > ~/.ssh/id_rsa.pub
    - echo "$TIBO_SSH_HOST" > ~/.ssh/known_hosts
    - ssh esibank@$IP_DOCKER "rm -r public-html/"
    - scp -r api/ esibank@$IP_DOCKER:public-html/
    - scp payfree-client/target/payfreeclt.jar esibank@$IP_DOCKER:public-html/install/payfreeclt.jar
    - scp nfc-reader-lib-repo/nfc-reader-lib.tgz esibank@$IP_DOCKER:public-html/install_dab_app/nfc-reader-lib.tgz
    - scp dab-app-tgz-repo/dab-appdab-app.tgz esibank@$IP_DOCKER:public-html/install_dab_app/dab-app.tgz
    - ssh esibank@$IP_DOCKER "sudo ./scriptDeployEsibank.sh"
    - ssh esibank@$IP_NOTIF "sudo ./scriptDeployNotifPush.sh"
  only:
    refs:
      - master