image: maven:3.3.9-jdk-8

variables:
  IP_NOTIFICATION: "192.154.88.164"
  IP_PUSH: "192.154.88.165"
  IP_REST: "192.154.88.162"
  IP_WEBAPP: "192.154.88.163"
  IP_SIEXT: "192.154.88.151"
  IP_DOCKER: "192.154.88.167"


stages:
  - build
  - deploy

deploy_push:
  stage: deploy
  script:
    - mkdir ~/.ssh
    - echo "$TIBO_SSH_PRIVATE" > ~/.ssh/id_rsa
    - chmod 700 ~/.ssh/id_rsa
    - ssh-keygen -f ~/.ssh/id_rsa -y > ~/.ssh/id_rsa.pub
    - echo "$TIBO_SSH_HOST" > ~/.ssh/known_hosts
    - ssh esibank@$IP_DOCKER "sudo ./scriptDeployEsibank.sh"
