image: maven:3.3.9-jdk-8

variables:
  IP_NOTIFICATION: "192.154.88.164"
  IP_PUSH: "192.154.88.165"

stages:
  - deploy

deploy_notification:
  stage: deploy
  script:
    - mkdir ~/.ssh
    - echo "$TIBO_SSH_PRIVATE" > ~/.ssh/id_rsa
    - chmod 700 ~/.ssh/id_rsa
    - ssh-keygen -f ~/.ssh/id_rsa -y > ~/.ssh/id_rsa.pub
    - echo "$TIBO_SSH_HOST" > ~/.ssh/known_hosts
    - cd esibank-utils/
    - mvn install
    - cd ~/notification-server/
    - mvn install -DskipTests
    - scp target/notificationserver.jar esibank@$IP_NOTIFICATION:/home/esibank/notificationserver.jar
    - ssh esibank@$IP_NOTIFICATION "sudo service notifserver restart"

deploy_push:
  stage: deploy
  script:
    - mkdir ~/.ssh
    - echo "TIBO_SSH_PRIVATE" > ~/.ssh/id_rsa
    - chmod 700 ~/.ssh/id_rsa
    - ssh-keygen -f ~/.ssh/id_rsa -y > ~/.ssh/id_rsa.pub
    - echo "TIBO_SSH_HOST" > ~/.ssh/known_hosts
    - cd esibank-utils/
    - mvn install
    - cd ~/notification-push-server/
    - mvn install -DskipTests
    - scp target/notificationpushserver-jar-with-dependencies.jar esibank@$IP_PUSH:/home/esibank/notificationpushserver.jar
    - ssh esibank@$IP_PUSH "sudo service pushserver restart"