image: maven:3.3.9-jdk-8

stages:
    - build
    - deploy

build:
    stage: build
    script:
        - mvn clean install
    artifacts:
        paths:
            - rest-server/target/serverrest.war

deploy_development:
    stage: deploy
    script:
    - mvn install
    - echo "$SSH_PRIVATE_KEY" > id_rsa
    - chmod 700 id_rsa
    - mkdir ~/.ssh
    - echo "$SSH_HOST_KEY" > ~/.ssh/known_hosts
    - scp -i id_rsa target/*.war deployer@$SSH_HOST:/home/esibank/app.war