image: marcolizza/docker-android-sdk:latest

variables:
  IP_WEBAPP: "192.154.88.163"

stages:
  - test
  - build
  - deploy

before_script:
  - chmod +x ./gradlew
  - mkdir ~/.ssh
  - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
  - chmod 700 ~/.ssh/id_rsa
  - ssh-keygen -f ~/.ssh/id_rsa -y > ~/.ssh/id_rsa.pub
  - echo "$SSH_HOST_KEYS" > ~/.ssh/known_hosts

test_apk:
  stage: test
  script:
    - ./gradlew test

build_apk:
  stage: build
  script:
    - ./gradlew assemble
  artifacts:
      paths:
      - app/build/outputs/apk/app-debug.apk
      
deploy_apk:
  stage: deploy
  dependencies:
    - build_apk
  script:
    - scp app/build/outputs/apk/app-debug.apk esibank@$IP_WEBAPP:/var/www/html/app-debug.apk
  when: on_success
  only:
    refs:
      - master